/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// node_modules/typed-assert/build/index.js
var require_build = __commonJS({
  "node_modules/typed-assert/build/index.js"(exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.check = exports.isPromise = exports.isInstanceOf = exports.isOneOfType = exports.isOneOf = exports.isOptionOfType = exports.isArrayOfType = exports.isRecordOfType = exports.isArray = exports.isRecordWithKeys = exports.isRecord = exports.isDate = exports.isString = exports.isNumber = exports.isBoolean = exports.isExactly = exports.isNotVoid = exports.isNotUndefined = exports.isNotNull = exports.isNever = exports.isUnknown = exports.safeJsonParse = exports.setBaseAssert = exports.assert = exports.defaultAssert = void 0;
    var expectedToBe = (type) => `expected to be ${type}`;
    var defaultAssert = (condition, message) => {
      if (!condition) {
        throw new TypeError(message);
      }
    };
    exports.defaultAssert = defaultAssert;
    var baseAssert = exports.defaultAssert;
    var assert = (condition, message) => baseAssert(condition, message);
    exports.assert = assert;
    function setBaseAssert(assert2) {
      if (assert2) {
        baseAssert = assert2;
      }
    }
    exports.setBaseAssert = setBaseAssert;
    var safeJsonParse = (json) => JSON.parse(json);
    exports.safeJsonParse = safeJsonParse;
    function isUnknown(_input) {
      return true;
    }
    exports.isUnknown = isUnknown;
    function isNever(_input, message = expectedToBe("unreachable")) {
      throw new TypeError(message);
    }
    exports.isNever = isNever;
    function isNotNull2(input, message = expectedToBe("not null")) {
      (0, exports.assert)(input !== null, message);
    }
    exports.isNotNull = isNotNull2;
    function isNotUndefined(input, message = expectedToBe("not undefined")) {
      (0, exports.assert)(input !== void 0, message);
    }
    exports.isNotUndefined = isNotUndefined;
    function isNotVoid(input, message = expectedToBe("neither null nor undefined")) {
      (0, exports.assert)(input !== null && input !== void 0, message);
    }
    exports.isNotVoid = isNotVoid;
    function isExactly(input, value, message = expectedToBe(`exactly ${value}`)) {
      (0, exports.assert)(input === value, message);
    }
    exports.isExactly = isExactly;
    function isBoolean(input, message = expectedToBe("a boolean")) {
      (0, exports.assert)(typeof input === "boolean", message);
    }
    exports.isBoolean = isBoolean;
    function isNumber(input, message = expectedToBe("a number")) {
      (0, exports.assert)(typeof input === "number", message);
    }
    exports.isNumber = isNumber;
    function isString(input, message = expectedToBe("a string")) {
      (0, exports.assert)(typeof input === "string", message);
    }
    exports.isString = isString;
    function isDate(input, message = expectedToBe("a Date")) {
      (0, exports.assert)(input instanceof Date, message);
    }
    exports.isDate = isDate;
    function isRecord(input, message = expectedToBe("a record")) {
      (0, exports.assert)(typeof input === "object", message);
      isNotNull2(input, message);
      for (const key of Object.keys(input)) {
        isString(key, message);
      }
    }
    exports.isRecord = isRecord;
    function isRecordWithKeys(input, keys, message = expectedToBe(`a record with keys ${keys.join(", ")}`)) {
      isRecord(input, message);
      for (const key of keys) {
        isNotUndefined(input[key]);
      }
    }
    exports.isRecordWithKeys = isRecordWithKeys;
    function isArray(input, message = expectedToBe("an array")) {
      (0, exports.assert)(Array.isArray(input), message);
    }
    exports.isArray = isArray;
    function isRecordOfType(input, assertT, message = expectedToBe("a record of given type"), itemMessage = expectedToBe("of given type")) {
      isRecord(input, message);
      for (const item of Object.values(input)) {
        assertT(item, itemMessage);
      }
    }
    exports.isRecordOfType = isRecordOfType;
    function isArrayOfType(input, assertT, message = expectedToBe("an array of given type"), itemMessage = expectedToBe("of given type")) {
      isArray(input, message);
      for (const item of input) {
        assertT(item, itemMessage);
      }
    }
    exports.isArrayOfType = isArrayOfType;
    function isOptionOfType(input, assertT, message = expectedToBe("option of given type")) {
      if (input === void 0) {
        return;
      }
      assertT(input, message);
    }
    exports.isOptionOfType = isOptionOfType;
    function isOneOf(input, values, message = expectedToBe(`one of ${values.join(", ")}`)) {
      (0, exports.assert)(values.includes(input), message);
    }
    exports.isOneOf = isOneOf;
    function isOneOfType(input, assertT, message = expectedToBe(`one of type`), itemMessage) {
      for (const assert2 of assertT) {
        try {
          assert2(input, itemMessage);
          return;
        } catch (_) {
        }
      }
      throw new TypeError(message);
    }
    exports.isOneOfType = isOneOfType;
    function isInstanceOf2(input, constructor, message = expectedToBe("an instance of given constructor")) {
      (0, exports.assert)(input instanceof constructor, message);
    }
    exports.isInstanceOf = isInstanceOf2;
    function isPromise(input, message = expectedToBe("a promise")) {
      isInstanceOf2(input, Promise, message);
    }
    exports.isPromise = isPromise;
    function check(assertT) {
      return (input) => {
        try {
          assertT(input);
          return true;
        } catch (_) {
          return false;
        }
      };
    }
    exports.check = check;
  }
});

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PersistentLinksPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_typed_assert = __toESM(require_build());

// src/patterns.ts
var BLOCK_ID = /\s+(\^[a-zA-Z0-9-]+)$/gm;
var NOT_LETTER_OR_NUMBER = /[^\p{Letter}\p{Number}]/gu;
var FILE_PATH_IN_LINK = /(\[\[).*(#)/;
var WIKILINK = /(!?\[\[)([^\]|#]*)(#[^\]|]*)?(\|[^\]]*)?(\]\])/;

// src/utils.ts
var obsidian = __toESM(require("obsidian"));
function getBlockIds(text) {
  return [...text.matchAll(BLOCK_ID)].map((match) => match[1]);
}
function normalizeHeading(text) {
  return text.replace(NOT_LETTER_OR_NUMBER, "");
}
function normalizeSubpath(text) {
  return text.split("#").map((segment) => normalizeHeading(segment)).join("#");
}
function getSubpathAliases(subpath) {
  const segments = subpath.split("#").filter(Boolean);
  if (segments.length <= 1) {
    return [];
  }
  return [segments.slice(1).join("#")];
}
function createHeadingKey(path, subpath) {
  return `${path}::${normalizeSubpath(subpath)}`;
}
function splitHeadingKey(key) {
  const separatorIndex = key.indexOf("::");
  return {
    path: key.slice(0, separatorIndex),
    subpath: key.slice(separatorIndex + 2)
  };
}
function parseLinkText(linkText) {
  const { path, subpath } = obsidian.parseLinktext(
    getRawLinkTarget(linkText)
  );
  return {
    path,
    subpath: subpath ? stripSubpathToken(subpath) : ""
  };
}
function stripSubpathToken(subpath) {
  return subpath.replace(/^#\^?/, "");
}
function replaceFilePathInLink(link, newPath) {
  return link.replace(FILE_PATH_IN_LINK, `$1${newPath}$2`);
}
function replaceLinkDestination(link, destination) {
  const match = link.match(WIKILINK);
  if (!match) {
    return destination.subpath ? replaceFilePathInLink(link, `${destination.path}#${destination.subpath}`) : replaceFilePathInLink(link, destination.path);
  }
  const [, prefix, , , alias = "", suffix] = match;
  const subpath = destination.subpath ? `#${destination.subpath}` : "";
  return `${prefix}${destination.path}${subpath}${alias}${suffix}`;
}
function getRawLinkTarget(linkText) {
  const wikilinkMatch = linkText.match(WIKILINK);
  if (!wikilinkMatch) {
    return linkText;
  }
  const [, , path = "", subpath = ""] = wikilinkMatch;
  return `${path}${subpath}`;
}
function isHeadingLink(linkText) {
  return linkText.includes("#") && !linkText.includes("#^");
}
function isBlockLink(linkText) {
  return linkText.includes("#^");
}
function redirectLinksInTextToNewPaths(linksWithPaths, text) {
  return linksWithPaths.slice().sort((a, b) => compareLinkOffsets(a.link, b.link)).reverse().reduce(
    (updatedText, { newPath, newSubpath, link: { position, original } }) => {
      const start = position.start.offset;
      const end = Math.max(position.end.offset, start + original.length);
      const updatedLink = replaceLinkDestination(original, {
        path: newPath,
        subpath: newSubpath ?? parseLinkText(original).subpath
      });
      return updatedText.substring(0, start) + updatedLink + updatedText.substring(end);
    },
    text
  );
}
function createUpdateNotice(results) {
  const fileCount = results.length;
  const linkCount = results.flatMap((f) => f.links).length;
  return `Updated ${linkCount} links in ${fileCount} files`;
}
function createRepairNotice(fixed, broken) {
  let result = "";
  if (fixed > 0) {
    result += `Repaired ${fixed} links`;
  }
  if (broken > 0) {
    result += `
${broken} links could not be repaired`;
  }
  return result;
}
function compareLinkOffsets(left, right) {
  return left.position.start.offset - right.position.start.offset;
}
function isSubpathInMetadata(subpath, metadata) {
  if (!metadata) {
    return false;
  }
  const { blocks, headings } = metadata;
  return blocks && subpath in blocks || headings && isSubpathInHeadingCache(subpath, headings);
}
function isSubpathInHeadingCache(subpath, headingCache) {
  const normalizedSubpaths = new Set(
    [subpath, ...getSubpathAliases(subpath)].map(
      (value) => normalizeSubpath(value)
    )
  );
  const normalizedLeaf = normalizeHeading(subpath);
  return getHeadingSnapshotsFromHeadingCache(headingCache).some(
    ({ heading, path }) => normalizedSubpaths.has(normalizeSubpath(path)) || getSubpathAliases(path).some(
      (alias) => normalizedSubpaths.has(normalizeSubpath(alias))
    ) || normalizeHeading(heading) === normalizedLeaf
  );
}
function getHeadingSnapshots(metadata) {
  return getHeadingSnapshotsFromHeadingCache(metadata?.headings ?? []);
}
function getHeadingSnapshotsFromText(text, parentSegments = []) {
  const rawHeadings = text.split(/\r?\n/).map((lineText, line) => parseHeadingLine(lineText, line)).filter((heading) => Boolean(heading));
  return buildHeadingSnapshots(rawHeadings, parentSegments);
}
function getHeadingPathSegmentsAtLine(editor, line, movedHeadingLevel) {
  const stack = [];
  for (let currentLine = 0; currentLine < Math.min(line, editor.lineCount()); currentLine += 1) {
    const heading = parseHeadingLine(editor.getLine(currentLine), currentLine);
    if (!heading) {
      continue;
    }
    while (stack.length > 0 && stack.at(-1).level >= heading.level) {
      stack.pop();
    }
    stack.push({
      heading: heading.heading,
      level: heading.level
    });
  }
  const candidateParents = typeof movedHeadingLevel === "number" ? stack.filter(({ level }) => level < movedHeadingLevel) : stack;
  if (candidateParents.length === 0) {
    return [];
  }
  return candidateParents.map(({ heading }) => heading);
}
function getLastHeadingSegment(subpath) {
  const segments = subpath.split("#").filter(Boolean);
  return segments.at(-1) ?? subpath;
}
function getHeadingSnapshotsFromHeadingCache(headingCache) {
  const rawHeadings = headingCache.map(
    ({ heading, level, position }) => ({
      heading,
      path: heading,
      line: position.start.line,
      level
    })
  );
  return buildHeadingSnapshots(rawHeadings);
}
function buildHeadingSnapshots(headings, parentSegments = []) {
  if (headings.length === 0) {
    return [];
  }
  const baseLevel = Math.min(...headings.map(({ level }) => level));
  const stack = [];
  return headings.map(({ heading, line, level }) => {
    const relativeLevel = level - baseLevel + 1;
    while (stack.length > 0 && stack.at(-1).level >= relativeLevel) {
      stack.pop();
    }
    stack.push({
      heading,
      level: relativeLevel,
      actualLevel: level
    });
    return {
      heading,
      path: [...parentSegments, ...stack.map(({ heading: heading2 }) => heading2)].join("#"),
      line,
      level
    };
  });
}
function parseHeadingLine(lineText, line) {
  const match = lineText.match(/^(#+)\s+(.*)$/);
  if (!match) {
    return null;
  }
  const [, markers, heading] = match;
  return {
    heading,
    path: heading,
    line,
    level: markers.length
  };
}

// src/main.ts
var DEFAULT_STATE = {
  headingRedirects: {}
};
var _PersistentLinksPlugin = class _PersistentLinksPlugin extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.sourceFile = null;
    this.pendingCutContext = null;
    this.recentRemovedContext = null;
    this.data = DEFAULT_STATE;
    this.headingSnapshots = /* @__PURE__ */ new Map();
    this.outgoingHeadingLinksBySource = /* @__PURE__ */ new Map();
    this.backlinksByTargetFile = /* @__PURE__ */ new Map();
    this.headingLinkCounts = /* @__PURE__ */ new Map();
    this.fileSubpathKeysByPath = /* @__PURE__ */ new Map();
    this.filePathsBySubpathKey = /* @__PURE__ */ new Map();
    this.isRebuildingState = false;
    this.isInitialized = false;
    this.hasHydratedFromResolved = false;
    this.initializationPromise = null;
    this.lastSavedState = "";
    this.redirectsDirty = false;
    this.resolvedRedirectCache = /* @__PURE__ */ new Map();
    this.isLinkPathBroken = ({
      path,
      subpath
    }) => {
      const toFile = this.getFileFromPathRelativeToActiveFile(path);
      if (toFile === null) {
        return true;
      }
      return !isSubpathInMetadata(
        subpath,
        this.app.metadataCache.getFileCache(toFile)
      );
    };
    this.handleEditorPaste = async (event, editor) => {
      await this.initializeStateIfNeeded();
      const clipboardContents = this.normalizeClipboardText(
        event?.clipboardData?.getData("text") ?? ""
      );
      if (!clipboardContents) {
        return;
      }
      const sourceFile = this.sourceFile ?? this.getRecentSourceFileForClipboard(clipboardContents);
      if (!sourceFile) {
        return;
      }
      const targetFile = this.getActiveFile();
      if (targetFile.path === sourceFile.path) {
        return;
      }
      const movedHeadingRedirects = this.getMovedHeadingRedirects(
        sourceFile,
        targetFile,
        clipboardContents,
        editor
      );
      const sourceSnapshots = this.getSourceHeadingSnapshotsForMove(sourceFile.path);
      const backlinksToUpdate = this.getMovedBacklinksToUpdate(
        sourceFile.path,
        clipboardContents,
        movedHeadingRedirects,
        sourceSnapshots
      );
      await this.registerMovedHeadings(
        sourceFile,
        targetFile,
        movedHeadingRedirects,
        sourceSnapshots,
        false
      );
      if (backlinksToUpdate.length === 0) {
        this.sourceFile = null;
        this.pendingCutContext = null;
        return;
      }
      window.setTimeout(() => {
        void this.redirectMovedLinks(
          backlinksToUpdate,
          sourceFile.path,
          targetFile,
          movedHeadingRedirects,
          sourceSnapshots
        ).then(() => {
          new import_obsidian.Notice(createUpdateNotice(backlinksToUpdate));
        });
      }, 0);
      this.sourceFile = null;
      this.pendingCutContext = null;
      this.recentRemovedContext = null;
    };
  }
  async onload() {
    const storedData = await this.loadData();
    this.data = {
      headingRedirects: this.deserializeRedirects(storedData)
    };
    this.lastSavedState = storedData?.redirects ? JSON.stringify(this.serializeData(this.data.headingRedirects)) : "";
    this.redirectsDirty = Boolean(
      storedData?.headingRedirects || Object.keys(this.data.headingRedirects).length
    );
    this.addCommand({
      id: "repair-links-in-file",
      name: "Repair links in current file",
      editorCallback: (editor) => {
        this.repairLinksInFile(editor);
      }
    });
    const body = document.querySelector("body");
    (0, import_typed_assert.isNotNull)(body);
    this.registerDomEvent(body, "cut", () => {
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      this.sourceFile = activeView?.file ?? null;
      if (!activeView?.editor || !activeView.file) {
        this.pendingCutContext = null;
        return;
      }
      const selectedText = activeView.editor.getSelection();
      if (!selectedText) {
        this.pendingCutContext = null;
        return;
      }
      const normalizedSelectedText = this.normalizeClipboardText(selectedText);
      const allHeadings = getHeadingSnapshotsFromText(activeView.editor.getValue());
      this.pendingCutContext = {
        allHeadings,
        fromLine: activeView.editor.getCursor("from").line,
        headings: allHeadings.filter(
          ({ line }) => line >= activeView.editor.getCursor("from").line && line <= activeView.editor.getCursor("to").line
        ),
        sourcePath: activeView.file.path,
        text: normalizedSelectedText,
        toLine: activeView.editor.getCursor("to").line
      };
    });
    this.registerEvent(
      this.app.workspace.on("editor-paste", (event, editor) => {
        void this.handleEditorPaste(event, editor);
      })
    );
    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        void this.handleMetadataChanged(file);
      })
    );
    this.registerEvent(
      this.app.metadataCache.on("resolved", () => {
        void this.handleMetadataResolved();
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          void this.handleFileRenamed(file, oldPath);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          void this.handleFileDeleted(file.path);
        }
      })
    );
    this.app.workspace.onLayoutReady(() => {
      if (!this.isInitialized) {
        void this.initializeStateIfNeeded();
      }
    });
  }
  async initializeStateIfNeeded() {
    if (this.isInitialized) {
      return;
    }
    if (this.initializationPromise) {
      await this.initializationPromise;
      return;
    }
    this.initializationPromise = (async () => {
      await this.waitForInitialMetadataWindow();
      await this.rebuildState();
      this.isInitialized = true;
      await this.saveSettings();
    })();
    try {
      await this.initializationPromise;
    } finally {
      this.initializationPromise = null;
    }
  }
  async handleMetadataResolved() {
    if (this.hasHydratedFromResolved) {
      return;
    }
    this.hasHydratedFromResolved = true;
    await this.forceRefreshState();
  }
  async waitForInitialMetadataWindow() {
    if (this.hasHydratedFromResolved) {
      return;
    }
    await new Promise((resolve) => {
      let isSettled = false;
      let timeoutId = 0;
      const onResolved = () => {
        finish();
      };
      const finish = () => {
        if (isSettled) {
          return;
        }
        isSettled = true;
        if (timeoutId) {
          window.clearTimeout(timeoutId);
        }
        this.app.metadataCache.off("resolved", onResolved);
        resolve();
      };
      this.app.metadataCache.on("resolved", onResolved);
      timeoutId = window.setTimeout(
        finish,
        _PersistentLinksPlugin.INITIAL_METADATA_WAIT_MS
      );
    });
  }
  async forceRefreshState() {
    await this.rebuildState();
    this.isInitialized = true;
    await this.saveSettings();
  }
  repairLinksInFile(editor) {
    const activeFileCache = this.app.metadataCache.getFileCache(
      this.getActiveFile()
    );
    if (!activeFileCache) {
      new import_obsidian.Notice("No links to repair");
      return;
    }
    const { links = [], embeds = [] } = activeFileCache;
    const { fixable, broken } = this.findNewPathsForBrokenLinks([
      ...links,
      ...embeds
    ]);
    if (fixable.length > 0) {
      editor.setValue(
        redirectLinksInTextToNewPaths(fixable, editor.getValue())
      );
    }
    new import_obsidian.Notice(createRepairNotice(fixable.length, broken.length));
  }
  findNewPathsForBrokenLinks(links) {
    return links.map((link) => ({ link, ...parseLinkText(link.link) })).filter(({ subpath }) => subpath).filter(this.isLinkPathBroken).map(({ link, subpath }) => ({
      link,
      destination: this.getMappedHeadingDestination(link.link) ?? this.findFileWithSubpathInCache(subpath, link.link)
    })).reduce(
      (result, { link, destination }) => {
        destination ? result.fixable.push({
          link,
          newPath: destination.path,
          newSubpath: destination.subpath
        }) : result.broken.push(link);
        return result;
      },
      { fixable: [], broken: [] }
    );
  }
  findFileWithSubpathInCache(subpath, linkText) {
    const candidates = this.getCandidatePathsForSubpath(subpath, linkText);
    for (const candidatePath of candidates) {
      const candidate = this.app.vault.getAbstractFileByPath(candidatePath);
      if (candidate instanceof import_obsidian.TFile && isSubpathInMetadata(subpath, this.app.metadataCache.getFileCache(candidate))) {
        return {
          path: this.app.metadataCache.fileToLinktext(
            candidate,
            this.getActiveFile().path
          ),
          subpath
        };
      }
    }
    if (this.isInitialized) {
      return null;
    }
    for (const file of this.app.vault.getMarkdownFiles()) {
      if (isSubpathInMetadata(subpath, this.app.metadataCache.getFileCache(file))) {
        return {
          path: this.app.metadataCache.fileToLinktext(
            file,
            this.getActiveFile().path
          ),
          subpath
        };
      }
    }
    return null;
  }
  getCandidatePathsForSubpath(subpath, linkText) {
    const subpathKey = this.createSubpathIndexKey(subpath, linkText);
    return [...this.filePathsBySubpathKey.get(subpathKey) ?? []];
  }
  getFileFromPathRelativeToActiveFile(path) {
    if (!path) {
      return this.getActiveFile();
    }
    return this.app.metadataCache.getFirstLinkpathDest(
      path,
      this.getActiveFile().path
    );
  }
  async redirectMovedLinks(links, sourceFilePath, targetFile, movedHeadingRedirects, sourceSnapshots) {
    const redirectMap = /* @__PURE__ */ new Map();
    for (const { from, to } of movedHeadingRedirects) {
      for (const variant of this.getHeadingRedirectVariants(
        from,
        to,
        sourceSnapshots
      )) {
        redirectMap.set(createHeadingKey("", variant.from), variant.to);
      }
    }
    return Promise.all(
      links.map(async ({ filePath, links: linksInFile }) => {
        const contents = await this.readFile(filePath);
        const targetFilePath = this.app.metadataCache.fileToLinktext(
          targetFile,
          filePath
        );
        const linksWithNewPath = linksInFile.map((link) => ({
          link,
          newPath: targetFilePath,
          newSubpath: isHeadingLink(link.link) ? redirectMap.get(createHeadingKey("", parseLinkText(link.link).subpath)) : void 0
        }));
        const updatedContents = redirectLinksInTextToNewPaths(
          linksWithNewPath,
          contents
        );
        return this.updateFile(filePath, updatedContents);
      })
    );
  }
  async handleMetadataChanged(file) {
    await this.initializeStateIfNeeded();
    const previousHeadings = this.headingSnapshots.get(file.path) ?? [];
    const backlinksToFile = this.getBacklinksToFile(file.path);
    const previousHeadingPaths = new Set(
      previousHeadings.map(({ path }) => createHeadingKey("", path))
    );
    this.indexFile(file);
    const currentHeadings = this.headingSnapshots.get(file.path) ?? [];
    const currentHeadingPaths = new Set(
      currentHeadings.map(({ path }) => createHeadingKey("", path))
    );
    const removedHeadings = previousHeadings.filter(
      ({ path }) => !currentHeadingPaths.has(createHeadingKey("", path))
    );
    const addedHeadings = currentHeadings.filter(
      ({ path }) => !previousHeadingPaths.has(createHeadingKey("", path))
    );
    if (removedHeadings.length > 0 && addedHeadings.length === 0) {
      this.recentRemovedContext = {
        allHeadings: previousHeadings,
        headings: removedHeadings,
        sourcePath: file.path,
        timestamp: Date.now()
      };
    } else if (addedHeadings.length > 0 && removedHeadings.length === 0) {
      await this.maybeHandleRecentHeadingMove(file, addedHeadings);
    } else if (this.recentRemovedContext?.sourcePath === file.path && previousHeadingPaths.size > 0) {
      this.recentRemovedContext = null;
    }
    if (previousHeadings.length > 0) {
      const redirects = this.findHeadingRedirects(
        file,
        previousHeadings,
        currentHeadings
      );
      if (redirects.length > 0) {
        for (const { from, to } of redirects) {
          for (const variant of this.getHeadingRedirectVariants(
            from,
            to,
            previousHeadings
          )) {
            if (!this.hasBacklinksToHeadingInSnapshots(
              file.path,
              variant.from,
              previousHeadings
            )) {
              continue;
            }
            this.registerHeadingRedirect(
              file.path,
              variant.from,
              file.path,
              variant.to
            );
          }
        }
        await this.updateBacklinksForHeadingRedirects(
          file,
          redirects,
          backlinksToFile,
          previousHeadings
        );
      }
    }
    await this.saveSettings();
  }
  async handleFileRenamed(file, oldPath) {
    await this.initializeStateIfNeeded();
    if (oldPath === file.path) {
      return;
    }
    const previousHeadings = this.headingSnapshots.get(oldPath) ?? [];
    this.removeIndexedLinksForSource(oldPath);
    this.removeIndexedSubpathsForFile(oldPath);
    this.headingSnapshots.delete(oldPath);
    this.moveBacklinksToRenamedTarget(oldPath, file.path);
    this.moveHeadingCountsForRenamedTarget(oldPath, file.path, previousHeadings);
    this.renameRedirectPaths(oldPath, file.path);
    this.indexFile(file);
    await this.saveSettings();
  }
  async handleFileDeleted(filePath) {
    await this.initializeStateIfNeeded();
    const previousHeadings = this.headingSnapshots.get(filePath) ?? [];
    this.removeIndexedLinksForSource(filePath);
    this.removeIndexedSubpathsForFile(filePath);
    this.removeBacklinksForDeletedTarget(filePath);
    this.removeHeadingCountsForDeletedTarget(filePath, previousHeadings);
    this.headingSnapshots.delete(filePath);
    this.removeRedirectsForDeletedPath(filePath);
    if (this.sourceFile?.path === filePath) {
      this.sourceFile = null;
    }
    await this.saveSettings();
  }
  async rebuildState() {
    if (this.isRebuildingState) {
      return;
    }
    this.isRebuildingState = true;
    try {
      this.headingSnapshots.clear();
      this.outgoingHeadingLinksBySource.clear();
      this.backlinksByTargetFile.clear();
      this.headingLinkCounts.clear();
      this.fileSubpathKeysByPath.clear();
      this.filePathsBySubpathKey.clear();
      for (const file of this.app.vault.getMarkdownFiles()) {
        this.indexFile(file);
      }
    } finally {
      this.isRebuildingState = false;
    }
  }
  indexFile(file) {
    this.headingSnapshots.set(file.path, this.getHeadingSnapshotsForFile(file));
    this.reindexSubpathsForFile(file);
    this.reindexLinksForFile(file);
  }
  getHeadingSnapshotsForFile(file) {
    return getHeadingSnapshots(this.app.metadataCache.getFileCache(file));
  }
  findHeadingRedirects(file, previousHeadings, currentHeadings) {
    const previousHeadingCountsByName = this.getHeadingCountsByName(
      previousHeadings
    );
    const previousHeadingKeys = new Set(
      previousHeadings.map(({ path }) => createHeadingKey("", path))
    );
    const currentHeadingKeys = new Set(
      currentHeadings.map(({ path }) => createHeadingKey("", path))
    );
    const currentHeadingsByLine = new Map(
      currentHeadings.map((heading) => [heading.line, heading])
    );
    const uniqueCurrentNewHeadingsByName = this.getUniqueCurrentNewHeadingsByName(
      currentHeadings,
      previousHeadingKeys
    );
    return previousHeadings.map((previousHeading) => {
      const previousHeadingKey = createHeadingKey("", previousHeading.path);
      if (currentHeadingKeys.has(previousHeadingKey)) {
        return null;
      }
      const movedHeadingWithSameName = previousHeadingCountsByName.get(previousHeading.heading) === 1 ? uniqueCurrentNewHeadingsByName.get(previousHeading.heading) : void 0;
      if (movedHeadingWithSameName) {
        return {
          from: previousHeading.path,
          to: movedHeadingWithSameName.path
        };
      }
      const updatedHeading = currentHeadingsByLine.get(previousHeading.line);
      if (!updatedHeading) {
        return null;
      }
      const updatedHeadingKey = createHeadingKey("", updatedHeading.path);
      if (previousHeadingKey === updatedHeadingKey || previousHeadingKeys.has(updatedHeadingKey)) {
        return null;
      }
      if (!this.hasBacklinksToHeadingInSnapshots(
        file.path,
        previousHeading.path,
        previousHeadings
      )) {
        return null;
      }
      return {
        from: previousHeading.path,
        to: updatedHeading.path
      };
    }).filter(
      (redirect) => Boolean(redirect)
    );
  }
  getUniqueCurrentNewHeadingsByName(currentHeadings, previousHeadingKeys) {
    const headingsByName = /* @__PURE__ */ new Map();
    for (const heading of currentHeadings) {
      if (previousHeadingKeys.has(createHeadingKey("", heading.path))) {
        continue;
      }
      const existingHeadings = headingsByName.get(heading.heading);
      if (existingHeadings) {
        existingHeadings.push(heading);
      } else {
        headingsByName.set(heading.heading, [heading]);
      }
    }
    return new Map(
      [...headingsByName.entries()].filter(([, headings]) => headings.length === 1).map(([headingName, [heading]]) => [headingName, heading])
    );
  }
  getHeadingCountsByName(headings) {
    const counts = /* @__PURE__ */ new Map();
    for (const { heading } of headings) {
      counts.set(heading, (counts.get(heading) ?? 0) + 1);
    }
    return counts;
  }
  getBacklinksToFile(targetPath) {
    return this.backlinksByTargetFile.get(targetPath) ?? _PersistentLinksPlugin.EMPTY_BACKLINKS_BY_SOURCE;
  }
  hasBacklinksToHeading(filePath, heading) {
    return this.hasBacklinksToHeadingInSnapshots(
      filePath,
      heading,
      this.headingSnapshots.get(filePath) ?? []
    );
  }
  hasBacklinksToHeadingInSnapshots(filePath, heading, snapshots) {
    const directCount = this.headingLinkCounts.get(createHeadingKey(filePath, heading)) ?? 0;
    if (directCount > 0) {
      return true;
    }
    for (const alias of getSubpathAliases(heading)) {
      if (this.countHeadingsWithSubpathAliasInSnapshots(snapshots, alias) === 1 && (this.headingLinkCounts.get(createHeadingKey(filePath, alias)) ?? 0) > 0) {
        return true;
      }
    }
    const leafHeading = getLastHeadingSegment(heading);
    if (leafHeading === heading) {
      return false;
    }
    if (this.countHeadingsWithLeafInSnapshots(snapshots, leafHeading) !== 1) {
      return false;
    }
    return (this.headingLinkCounts.get(createHeadingKey(filePath, leafHeading)) ?? 0) > 0;
  }
  countHeadingsWithLeafInSnapshots(snapshots, heading) {
    return snapshots.filter(
      ({ heading: currentHeading }) => currentHeading === heading
    ).length;
  }
  countHeadingsWithSubpathAliasInSnapshots(snapshots, subpathAlias) {
    return snapshots.filter(
      ({ path }) => getSubpathAliases(path).includes(subpathAlias)
    ).length;
  }
  getHeadingMatchKeys(filePath, heading, snapshots) {
    const keys = [createHeadingKey(filePath, heading)];
    for (const alias of getSubpathAliases(heading)) {
      if (this.countHeadingsWithSubpathAliasInSnapshots(snapshots, alias) === 1) {
        keys.push(createHeadingKey(filePath, alias));
      }
    }
    const leafHeading = getLastHeadingSegment(heading);
    if (this.countHeadingsWithLeafInSnapshots(snapshots, leafHeading) === 1) {
      keys.push(createHeadingKey(filePath, leafHeading));
    }
    return [...new Set(keys)];
  }
  getHeadingRedirectVariants(from, to, snapshots) {
    const variants = [{ from, to }];
    const fromAliases = getSubpathAliases(from);
    const toAliases = getSubpathAliases(to);
    for (const [index, alias] of fromAliases.entries()) {
      if (this.countHeadingsWithSubpathAliasInSnapshots(snapshots, alias) !== 1) {
        continue;
      }
      variants.push({
        from: alias,
        to: toAliases[index] ?? to
      });
    }
    const leafHeading = getLastHeadingSegment(from);
    if (leafHeading !== from && this.countHeadingsWithLeafInSnapshots(snapshots, leafHeading) === 1) {
      variants.push({
        from: leafHeading,
        to: getLastHeadingSegment(to)
      });
    }
    return variants.filter(
      ({ from: variantFrom }, index, allVariants) => allVariants.findIndex(({ from: from2 }) => from2 === variantFrom) === index
    );
  }
  getSourceHeadingSnapshotsForMove(sourceFilePath) {
    if (this.pendingCutContext && this.pendingCutContext.sourcePath === sourceFilePath) {
      return this.pendingCutContext.allHeadings;
    }
    if (this.recentRemovedContext && this.recentRemovedContext.sourcePath === sourceFilePath) {
      return this.recentRemovedContext.allHeadings;
    }
    return this.headingSnapshots.get(sourceFilePath) ?? [];
  }
  getMovedHeadingRedirects(sourceFile, targetFile, clipboardContents, editor) {
    const sourceHeadings = this.getSelectedHeadingSnapshots(sourceFile, clipboardContents);
    if (sourceHeadings.length === 0) {
      return [];
    }
    const movedRootLevel = sourceHeadings[0]?.level;
    const targetParentSegments = getHeadingPathSegmentsAtLine(
      editor,
      editor.getCursor("from").line,
      movedRootLevel
    );
    const targetHeadings = getHeadingSnapshotsFromText(
      clipboardContents,
      targetFile.path === sourceFile.path ? [] : targetParentSegments
    );
    return sourceHeadings.map((sourceHeading, index) => {
      const targetHeading = targetHeadings[index];
      if (!targetHeading) {
        return null;
      }
      return {
        from: sourceHeading.path,
        to: targetHeading.path
      };
    }).filter(
      (redirect) => Boolean(redirect)
    );
  }
  getSelectedHeadingSnapshots(sourceFile, clipboardContents) {
    if (this.pendingCutContext && this.pendingCutContext.sourcePath === sourceFile.path && this.pendingCutContext.text === clipboardContents) {
      return this.pendingCutContext.headings;
    }
    if (this.recentRemovedContext && this.recentRemovedContext.sourcePath === sourceFile.path && this.isRecentRemovedContextMatch(clipboardContents)) {
      return this.recentRemovedContext.headings;
    }
    const allHeadings = this.headingSnapshots.get(sourceFile.path) ?? this.getHeadingSnapshotsForFile(sourceFile);
    const clipboardHeadings = getHeadingSnapshotsFromText(clipboardContents);
    if (clipboardHeadings.length === 0) {
      return [];
    }
    const firstHeading = clipboardHeadings[0];
    const matchedIndex = allHeadings.findIndex(
      ({ heading }) => heading === firstHeading.heading
    );
    if (matchedIndex < 0) {
      return [];
    }
    return allHeadings.slice(matchedIndex, matchedIndex + clipboardHeadings.length);
  }
  async maybeHandleRecentHeadingMove(targetFile, addedHeadings) {
    if (!this.recentRemovedContext) {
      return;
    }
    if (Date.now() - this.recentRemovedContext.timestamp > _PersistentLinksPlugin.RECENT_MOVE_WINDOW_MS) {
      this.recentRemovedContext = null;
      return;
    }
    if (this.recentRemovedContext.sourcePath === targetFile.path) {
      return;
    }
    const redirects = this.matchRemovedHeadingsToAddedHeadings(addedHeadings);
    if (redirects.length === 0) {
      return;
    }
    const sourceFile = this.app.vault.getAbstractFileByPath(
      this.recentRemovedContext.sourcePath
    );
    if (!(sourceFile instanceof import_obsidian.TFile)) {
      this.recentRemovedContext = null;
      return;
    }
    const sourceSnapshots = this.recentRemovedContext.allHeadings;
    const backlinksToUpdate = this.getBacklinksToUpdateForRedirects(
      this.recentRemovedContext.sourcePath,
      redirects,
      sourceSnapshots
    );
    await this.registerMovedHeadings(
      sourceFile,
      targetFile,
      redirects,
      sourceSnapshots
    );
    if (backlinksToUpdate.length > 0) {
      await this.redirectMovedLinks(
        backlinksToUpdate,
        this.recentRemovedContext.sourcePath,
        targetFile,
        redirects,
        sourceSnapshots
      );
    }
    this.recentRemovedContext = null;
  }
  matchRemovedHeadingsToAddedHeadings(addedHeadings) {
    if (!this.recentRemovedContext) {
      return [];
    }
    const matched = [];
    let searchStartIndex = 0;
    for (const removedHeading of this.recentRemovedContext.headings) {
      const matchIndex = addedHeadings.findIndex(
        (addedHeading, index) => index >= searchStartIndex && addedHeading.heading === removedHeading.heading
      );
      if (matchIndex < 0) {
        return [];
      }
      matched.push({
        from: removedHeading.path,
        to: addedHeadings[matchIndex].path
      });
      searchStartIndex = matchIndex + 1;
    }
    return matched;
  }
  getRecentSourceFileForClipboard(clipboardContents) {
    if (!this.isRecentRemovedContextMatch(clipboardContents)) {
      return null;
    }
    const sourceFile = this.app.vault.getAbstractFileByPath(
      this.recentRemovedContext.sourcePath
    );
    return sourceFile instanceof import_obsidian.TFile ? sourceFile : null;
  }
  isRecentRemovedContextMatch(clipboardContents) {
    if (!this.recentRemovedContext) {
      return false;
    }
    if (Date.now() - this.recentRemovedContext.timestamp > _PersistentLinksPlugin.RECENT_MOVE_WINDOW_MS) {
      this.recentRemovedContext = null;
      return false;
    }
    const clipboardHeadings = getHeadingSnapshotsFromText(clipboardContents);
    if (clipboardHeadings.length === 0) {
      return false;
    }
    if (clipboardHeadings.length !== this.recentRemovedContext.headings.length) {
      return false;
    }
    return clipboardHeadings.every((heading, index) => {
      const removedHeading = this.recentRemovedContext.headings[index];
      return heading.heading === removedHeading.heading;
    });
  }
  normalizeClipboardText(text) {
    return text.replace(/\r\n?/g, "\n");
  }
  getBacklinksToUpdateForRedirects(sourceFilePath, redirects, sourceSnapshots) {
    const movedHeadingKeys = new Set(
      redirects.flatMap(
        ({ from }) => this.getHeadingMatchKeys(sourceFilePath, from, sourceSnapshots)
      )
    );
    return [...this.getBacklinksToFile(sourceFilePath).entries()].map(([filePath, links]) => ({
      filePath,
      links: links.filter((link) => {
        if (!isHeadingLink(link.link)) {
          return false;
        }
        const { subpath } = parseLinkText(link.link);
        if (!subpath) {
          return false;
        }
        return movedHeadingKeys.has(createHeadingKey(sourceFilePath, subpath));
      })
    })).filter(({ links }) => links.length > 0);
  }
  getMovedBacklinksToUpdate(sourceFilePath, clipboardContents, movedHeadingRedirects, sourceSnapshots) {
    const blockIds = new Set(getBlockIds(clipboardContents));
    const movedHeadingKeys = new Set(
      movedHeadingRedirects.flatMap(
        ({ from }) => this.getHeadingMatchKeys(sourceFilePath, from, sourceSnapshots)
      )
    );
    return [...this.getBacklinksToFile(sourceFilePath).entries()].map(([filePath, links]) => ({
      filePath,
      links: links.filter((link) => {
        if (isBlockLink(link.link)) {
          return [...blockIds].some((blockId) => link.link.includes(blockId));
        }
        if (!isHeadingLink(link.link)) {
          return false;
        }
        const { subpath } = parseLinkText(link.link);
        if (!subpath) {
          return false;
        }
        return movedHeadingKeys.has(createHeadingKey(sourceFilePath, subpath));
      })
    })).filter(({ links }) => links.length > 0);
  }
  async registerMovedHeadings(sourceFile, targetFile, redirects, sourceSnapshots, persist = true) {
    let hasChanges = false;
    for (const { from, to } of redirects) {
      if (!this.hasBacklinksToHeading(sourceFile.path, from)) {
        continue;
      }
      for (const variant of this.getHeadingRedirectVariants(
        from,
        to,
        sourceSnapshots
      )) {
        if (!this.hasBacklinksToHeadingInSnapshots(
          sourceFile.path,
          variant.from,
          sourceSnapshots
        )) {
          continue;
        }
        this.registerHeadingRedirect(
          sourceFile.path,
          variant.from,
          targetFile.path,
          variant.to
        );
        hasChanges = true;
      }
    }
    if (hasChanges && persist) {
      await this.saveSettings();
    }
  }
  registerHeadingRedirect(fromPath, fromHeading, toPath, toHeading) {
    const sourceKey = createHeadingKey(fromPath, fromHeading);
    const destination = {
      path: toPath,
      subpath: toHeading
    };
    if (createHeadingKey(destination.path, destination.subpath ?? "") === sourceKey) {
      if (sourceKey in this.data.headingRedirects) {
        this.redirectsDirty = true;
      }
      this.clearResolvedRedirectCache();
      delete this.data.headingRedirects[sourceKey];
      return;
    }
    if (this.data.headingRedirects[sourceKey]?.path !== destination.path || this.data.headingRedirects[sourceKey]?.subpath !== destination.subpath) {
      this.redirectsDirty = true;
      this.clearResolvedRedirectCache();
    }
    this.data.headingRedirects[sourceKey] = destination;
  }
  getMappedHeadingDestination(linkText) {
    if (!isHeadingLink(linkText)) {
      return null;
    }
    const { path, subpath } = parseLinkText(linkText);
    if (!subpath) {
      return null;
    }
    let currentFile = this.getFileFromPathRelativeToActiveFile(path);
    let currentSubpath = subpath;
    if (!currentFile) {
      return null;
    }
    const latestDestination = this.resolveFinalDestinationForKey(
      createHeadingKey(currentFile.path, currentSubpath)
    );
    if (!latestDestination) {
      return null;
    }
    currentSubpath = latestDestination.subpath ?? currentSubpath;
    const resolvedDestination = this.app.vault.getAbstractFileByPath(
      latestDestination.path
    );
    if (resolvedDestination instanceof import_obsidian.TFile) {
      currentFile = resolvedDestination;
    }
    return {
      path: this.app.metadataCache.fileToLinktext(
        currentFile,
        this.getActiveFile().path
      ),
      subpath: currentSubpath
    };
  }
  async updateBacklinksForHeadingRedirects(targetFile, redirects, backlinks, sourceSnapshots) {
    const redirectMap = /* @__PURE__ */ new Map();
    for (const { from, to } of redirects) {
      for (const variant of this.getHeadingRedirectVariants(
        from,
        to,
        sourceSnapshots
      )) {
        redirectMap.set(
          createHeadingKey(targetFile.path, variant.from),
          variant.to
        );
      }
    }
    const updates = [...backlinks.entries()].map(([filePath, links]) => ({
      filePath,
      links: links.filter(({ link }) => isHeadingLink(link)).map((link) => {
        const { subpath } = parseLinkText(link.link);
        if (!subpath) {
          return null;
        }
        const redirectedHeading = redirectMap.get(
          createHeadingKey(targetFile.path, subpath)
        );
        if (!redirectedHeading) {
          return null;
        }
        return {
          link,
          newPath: this.app.metadataCache.fileToLinktext(targetFile, filePath),
          newSubpath: redirectedHeading
        };
      }).filter((link) => Boolean(link))
    })).filter(({ links }) => links.length > 0);
    await Promise.all(
      updates.map(async ({ filePath, links }) => {
        const contents = await this.readFile(filePath);
        const updatedContents = redirectLinksInTextToNewPaths(links, contents);
        return this.updateFile(filePath, updatedContents);
      })
    );
  }
  reindexLinksForFile(file) {
    this.removeIndexedLinksForSource(file.path);
    const indexedLinks = this.extractIndexedHeadingLinks(file);
    if (indexedLinks.length === 0) {
      return;
    }
    this.outgoingHeadingLinksBySource.set(file.path, indexedLinks);
    for (const indexedLink of indexedLinks) {
      const backlinks = this.backlinksByTargetFile.get(indexedLink.targetPath) ?? /* @__PURE__ */ new Map();
      const linksFromSource = backlinks.get(indexedLink.sourcePath);
      if (linksFromSource) {
        linksFromSource.push(indexedLink.link);
      } else {
        backlinks.set(indexedLink.sourcePath, [indexedLink.link]);
      }
      this.backlinksByTargetFile.set(indexedLink.targetPath, backlinks);
      this.adjustHeadingLinkCount(
        createHeadingKey(indexedLink.targetPath, indexedLink.subpath),
        1
      );
    }
  }
  removeIndexedLinksForSource(sourcePath) {
    const previousLinks = this.outgoingHeadingLinksBySource.get(sourcePath);
    if (!previousLinks) {
      return;
    }
    const affectedTargets = new Set(
      previousLinks.map(({ targetPath }) => targetPath)
    );
    for (const previousLink of previousLinks) {
      this.adjustHeadingLinkCount(
        createHeadingKey(previousLink.targetPath, previousLink.subpath),
        -1
      );
    }
    for (const targetPath of affectedTargets) {
      const backlinks = this.backlinksByTargetFile.get(targetPath);
      if (!backlinks) {
        continue;
      }
      backlinks.delete(sourcePath);
      if (backlinks.size === 0) {
        this.backlinksByTargetFile.delete(targetPath);
      }
    }
    this.outgoingHeadingLinksBySource.delete(sourcePath);
  }
  extractIndexedHeadingLinks(file) {
    return this.getLinksFromMetadata(this.app.metadataCache.getFileCache(file)).filter(({ link }) => isHeadingLink(link)).map((link) => {
      const { subpath } = parseLinkText(link.link);
      const targetFile = this.resolveLinkedFile(file, link.link);
      if (!subpath || !targetFile) {
        return null;
      }
      return {
        sourcePath: file.path,
        targetPath: targetFile.path,
        subpath,
        link: this.toLinkReference(link)
      };
    }).filter(
      (indexedLink) => Boolean(indexedLink)
    );
  }
  adjustHeadingLinkCount(headingKey, delta) {
    const nextCount = (this.headingLinkCounts.get(headingKey) ?? 0) + delta;
    if (headingKey in this.data.headingRedirects) {
      this.redirectsDirty = true;
    }
    if (nextCount <= 0) {
      this.headingLinkCounts.delete(headingKey);
      return;
    }
    this.headingLinkCounts.set(headingKey, nextCount);
  }
  reindexSubpathsForFile(file) {
    this.removeIndexedSubpathsForFile(file.path);
    const subpathKeys = this.getSubpathKeysForFile(file);
    if (subpathKeys.length === 0) {
      return;
    }
    this.fileSubpathKeysByPath.set(file.path, subpathKeys);
    for (const subpathKey of subpathKeys) {
      const paths = this.filePathsBySubpathKey.get(subpathKey) ?? /* @__PURE__ */ new Set();
      paths.add(file.path);
      this.filePathsBySubpathKey.set(subpathKey, paths);
    }
  }
  removeIndexedSubpathsForFile(filePath) {
    const previousKeys = this.fileSubpathKeysByPath.get(filePath);
    if (!previousKeys) {
      return;
    }
    for (const previousKey of previousKeys) {
      const paths = this.filePathsBySubpathKey.get(previousKey);
      if (!paths) {
        continue;
      }
      paths.delete(filePath);
      if (paths.size === 0) {
        this.filePathsBySubpathKey.delete(previousKey);
      }
    }
    this.fileSubpathKeysByPath.delete(filePath);
  }
  getSubpathKeysForFile(file) {
    const headingKeys = (this.headingSnapshots.get(file.path) ?? []).flatMap(
      ({ heading, path }) => [
        this.createSubpathIndexKey(heading, "heading"),
        this.createSubpathIndexKey(path, "heading"),
        ...getSubpathAliases(path).map(
          (alias) => this.createSubpathIndexKey(alias, "heading")
        )
      ]
    );
    const metadata = this.app.metadataCache.getFileCache(file);
    const blockKeys = Object.keys(metadata?.blocks ?? {}).map(
      (blockId) => this.createSubpathIndexKey(blockId, "block")
    );
    return [.../* @__PURE__ */ new Set([...headingKeys, ...blockKeys])];
  }
  createSubpathIndexKey(subpath, linkOrType) {
    return isBlockLink(linkOrType) || linkOrType === "block" ? `b:${subpath}` : `h:${normalizeSubpath(subpath)}`;
  }
  moveBacklinksToRenamedTarget(oldPath, newPath) {
    const backlinks = this.backlinksByTargetFile.get(oldPath);
    if (!backlinks) {
      return;
    }
    const mergedBacklinks = this.backlinksByTargetFile.get(newPath) ?? /* @__PURE__ */ new Map();
    for (const [sourcePath, links] of backlinks.entries()) {
      const existingLinks = mergedBacklinks.get(sourcePath);
      if (existingLinks) {
        existingLinks.push(...links);
      } else {
        mergedBacklinks.set(sourcePath, [...links]);
      }
    }
    this.backlinksByTargetFile.set(newPath, mergedBacklinks);
    this.backlinksByTargetFile.delete(oldPath);
  }
  moveHeadingCountsForRenamedTarget(oldPath, newPath, previousHeadings) {
    const uniqueHeadings = new Set(
      previousHeadings.flatMap(({ heading, path }) => [heading, path])
    );
    for (const heading of uniqueHeadings) {
      const oldKey = createHeadingKey(oldPath, heading);
      const count = this.headingLinkCounts.get(oldKey);
      if (!count) {
        continue;
      }
      this.headingLinkCounts.delete(oldKey);
      this.headingLinkCounts.set(createHeadingKey(newPath, heading), count);
    }
  }
  removeBacklinksForDeletedTarget(filePath) {
    this.backlinksByTargetFile.delete(filePath);
  }
  removeHeadingCountsForDeletedTarget(filePath, previousHeadings) {
    const uniqueHeadings = new Set(
      previousHeadings.flatMap(({ heading, path }) => [heading, path])
    );
    for (const heading of uniqueHeadings) {
      this.headingLinkCounts.delete(createHeadingKey(filePath, heading));
    }
  }
  renameRedirectPaths(oldPath, newPath) {
    const updatedRedirects = {};
    let changed = false;
    for (const [sourceKey, destination] of Object.entries(
      this.data.headingRedirects
    )) {
      const { path, subpath } = splitHeadingKey(sourceKey);
      const nextSourceKey = path === oldPath ? createHeadingKey(newPath, subpath) : sourceKey;
      const nextPath = destination.path === oldPath ? newPath : destination.path;
      changed = changed || nextSourceKey !== sourceKey || nextPath !== destination.path;
      updatedRedirects[nextSourceKey] = {
        path: nextPath,
        subpath: destination.subpath
      };
    }
    if (changed) {
      this.redirectsDirty = true;
      this.clearResolvedRedirectCache();
    }
    this.data.headingRedirects = updatedRedirects;
  }
  removeRedirectsForDeletedPath(filePath) {
    const updatedRedirects = {};
    let changed = false;
    for (const [sourceKey, destination] of Object.entries(
      this.data.headingRedirects
    )) {
      const { path } = splitHeadingKey(sourceKey);
      if (path === filePath || destination.path === filePath) {
        changed = true;
        continue;
      }
      updatedRedirects[sourceKey] = destination;
    }
    if (changed) {
      this.redirectsDirty = true;
      this.clearResolvedRedirectCache();
    }
    this.data.headingRedirects = updatedRedirects;
  }
  resolveLinkedFile(sourceFile, linkText) {
    const { path } = parseLinkText(linkText);
    if (!path) {
      return sourceFile;
    }
    return this.app.metadataCache.getFirstLinkpathDest(path, sourceFile.path);
  }
  getLinksFromMetadata(metadata) {
    return [...metadata?.links ?? [], ...metadata?.embeds ?? []];
  }
  getFile(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    (0, import_typed_assert.isInstanceOf)(file, import_obsidian.TFile);
    return file;
  }
  async readFile(path) {
    return this.app.vault.read(this.getFile(path));
  }
  async updateFile(path, newContents) {
    return this.app.vault.modify(this.getFile(path), newContents);
  }
  getActiveFile() {
    const activeFile = this.app.workspace.getActiveFile();
    (0, import_typed_assert.isNotNull)(activeFile);
    return activeFile;
  }
  async saveSettings() {
    if (!this.redirectsDirty) {
      return;
    }
    this.data.headingRedirects = this.compactHeadingRedirects();
    this.clearResolvedRedirectCache();
    const persistedData = this.serializeData(this.data.headingRedirects);
    const serializedState = JSON.stringify(persistedData);
    if (serializedState === this.lastSavedState) {
      this.redirectsDirty = false;
      return;
    }
    this.lastSavedState = serializedState;
    this.redirectsDirty = false;
    await this.saveData(persistedData);
  }
  compactHeadingRedirects() {
    const compacted = {};
    const sourceKeys = Object.keys(this.data.headingRedirects);
    for (const sourceKey of sourceKeys) {
      if (!this.headingLinkCounts.has(sourceKey)) {
        continue;
      }
      const finalDestination = this.resolveFinalDestinationForKey(sourceKey);
      if (!finalDestination?.subpath) {
        continue;
      }
      if (!this.destinationExists(finalDestination)) {
        continue;
      }
      if (createHeadingKey(finalDestination.path, finalDestination.subpath) === sourceKey) {
        continue;
      }
      compacted[sourceKey] = finalDestination;
    }
    if (Object.keys(compacted).length !== sourceKeys.length) {
      this.redirectsDirty = true;
    }
    return compacted;
  }
  resolveFinalDestinationForKey(sourceKey) {
    if (this.resolvedRedirectCache.has(sourceKey)) {
      return this.resolvedRedirectCache.get(sourceKey) ?? null;
    }
    let currentKey = sourceKey;
    let latestDestination = this.data.headingRedirects[sourceKey] ?? null;
    const visited = /* @__PURE__ */ new Set();
    while (latestDestination && !visited.has(currentKey)) {
      visited.add(currentKey);
      const nextKey = latestDestination.subpath ? createHeadingKey(latestDestination.path, latestDestination.subpath) : null;
      if (!nextKey || !this.data.headingRedirects[nextKey]) {
        return latestDestination;
      }
      currentKey = nextKey;
      latestDestination = this.data.headingRedirects[nextKey];
    }
    this.resolvedRedirectCache.set(sourceKey, latestDestination);
    return latestDestination;
  }
  destinationExists(destination) {
    const file = this.app.vault.getAbstractFileByPath(destination.path);
    if (!(file instanceof import_obsidian.TFile)) {
      return false;
    }
    return destination.subpath ? isSubpathInMetadata(
      destination.subpath,
      this.app.metadataCache.getFileCache(file)
    ) : true;
  }
  deserializeRedirects(storedData) {
    const redirects = {};
    if (storedData?.redirects) {
      for (const [sourcePath, sourceRedirects] of Object.entries(
        storedData.redirects
      )) {
        for (const [normalizedSubpath, destination] of Object.entries(
          sourceRedirects
        )) {
          redirects[createHeadingKey(sourcePath, normalizedSubpath)] = {
            path: destination[0],
            subpath: destination[1]
          };
        }
      }
      return redirects;
    }
    return {
      ...storedData?.headingRedirects
    };
  }
  serializeData(headingRedirects) {
    return {
      redirects: this.serializeRedirects(headingRedirects)
    };
  }
  serializeRedirects(headingRedirects) {
    const redirects = {};
    for (const [sourceKey, destination] of Object.entries(headingRedirects)) {
      if (!destination.subpath) {
        continue;
      }
      const { path, subpath } = splitHeadingKey(sourceKey);
      const sourceRedirects = redirects[path] ?? {};
      sourceRedirects[subpath] = [destination.path, destination.subpath];
      redirects[path] = sourceRedirects;
    }
    return redirects;
  }
  toLinkReference(link) {
    return {
      link: link.link,
      original: link.original,
      position: link.position
    };
  }
  clearResolvedRedirectCache() {
    this.resolvedRedirectCache.clear();
  }
};
_PersistentLinksPlugin.EMPTY_BACKLINKS_BY_SOURCE = /* @__PURE__ */ new Map();
_PersistentLinksPlugin.INITIAL_METADATA_WAIT_MS = 1500;
_PersistentLinksPlugin.RECENT_MOVE_WINDOW_MS = 15e3;
var PersistentLinksPlugin = _PersistentLinksPlugin;
