/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => IntervalWorkspaceSaverPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  intervalSeconds: 30,
  isEnabled: true,
  showNotice: true,
  colors: {
    idle: "#3B82F6",
    saving: "#F59E0B",
    saved: "#22C55E",
    error: "#EF4444",
    disabled: "#6B7280",
    notfound: "#8B5CF6"
  }
};
var IntervalWorkspaceSaverPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new IntervalWorkspaceSaverSettingTab(this.app, this));
    this.createStatusBar();
    this.startSaveInterval();
  }
  onunload() {
    this.stopSaveInterval();
    if (this.statusBarItem) {
      this.statusBarItem.remove();
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    if (this.settings.intervalMinutes !== void 0) {
      this.settings.intervalSeconds = this.settings.intervalMinutes * 60;
      delete this.settings.intervalMinutes;
      await this.saveSettings();
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  getContrastColor(hexColor) {
    if (!hexColor || !hexColor.trim()) return "#FFFFFF";
    const hex = hexColor.replace("#", "");
    const r = parseInt(hex.substr(0, 2), 16);
    const g = parseInt(hex.substr(2, 2), 16);
    const b = parseInt(hex.substr(4, 2), 16);
    const brightness = (r * 299 + g * 587 + b * 114) / 1000;
    return brightness > 128 ? "#000000" : "#FFFFFF";
  }
  applyStatusBarColors() {
    if (!this.statusBarItem) return;
    const colors = (this.settings == null ? void 0 : this.settings.colors) || {};
    const setVar = (name, value) => {
      if (value && typeof value === "string" && value.trim()) {
        this.statusBarItem.style.setProperty(name, value.trim());
      } else {
        this.statusBarItem.style.removeProperty(name);
      }
    };
    const setVarWithContrast = (bgName, colorName, bgValue) => {
      setVar(bgName, bgValue);
      if (bgValue && bgValue.trim()) {
        const textColor = this.getContrastColor(bgValue);
        setVar(colorName, textColor);
      } else {
        this.statusBarItem.style.removeProperty(colorName);
      }
    };
    setVarWithContrast("--ws-bg-idle", "--ws-color-idle", colors.idle);
    setVarWithContrast("--ws-bg-saving", "--ws-color-saving", colors.saving);
    setVarWithContrast("--ws-bg-saved", "--ws-color-saved", colors.saved);
    setVarWithContrast("--ws-bg-error", "--ws-color-error", colors.error);
    setVarWithContrast("--ws-bg-disabled", "--ws-color-disabled", colors.disabled);
    setVarWithContrast("--ws-bg-notfound", "--ws-color-notfound", colors.notfound);
  }
  createStatusBar() {
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.addClass("workspace-saver-status-bar");
    this.applyStatusBarColors();
    this.updateStatusBar();
    this.statusBarItem.setAttr("title", "点击强制保存工作区");
    this.statusBarItem.addEventListener("click", async () => {
      await this.saveCurrentWorkspace(true);
    });
  }
  getCurrentWorkspaceName() {
    const workspacesPlugin = this.getWorkspacesPlugin();
    if (!workspacesPlugin?.enabled || !workspacesPlugin?.instance) {
      return null;
    }
    const instance = workspacesPlugin.instance;

    if (instance.activeWorkspace?.name) {
      return instance.activeWorkspace.name;
    }

    const workspaces = instance.workspaces || {};
    const workspaceNames = Object.keys(workspaces);

    if (workspaceNames.length > 0) {
      return workspaceNames[workspaceNames.length - 1];
    }

    return null;
  }

  updateStatusBar(status = "idle") {
    if (!this.statusBarItem) return;
    this.applyStatusBarColors();

    const statusBarEl = this.statusBarItem;
    statusBarEl.removeClass("idle");
    statusBarEl.removeClass("saving");
    statusBarEl.removeClass("saved");
    statusBarEl.removeClass("error");
    statusBarEl.removeClass("disabled");
    statusBarEl.removeClass("notfound");

    switch (status) {
      case "saving":
        statusBarEl.setText(`💾 保存中`);
        statusBarEl.addClass("saving");
        break;
      case "saved":
        statusBarEl.setText(`✅ 已保存`);
        statusBarEl.addClass("saved");
        break;
      case "error":
        statusBarEl.setText(`⚠️ 保存失败`);
        statusBarEl.addClass("error");
        break;
      case "disabled":
        statusBarEl.setText(`🔴 已禁用`);
        statusBarEl.addClass("disabled");
        break;
      case "notfound":
        statusBarEl.setText(`❌ 未找到工作区`);
        statusBarEl.addClass("notfound");
        break;
      default:
        if (this.settings.isEnabled) {
          statusBarEl.setText(`🔄️ 待保存`);
          statusBarEl.addClass("idle");
        } else {
          statusBarEl.setText(`🔴 已禁用`);
          statusBarEl.addClass("disabled");
        }
    }
  }
  startSaveInterval() {
    if (import_obsidian.Platform.isMobile) {
      return;
    }
    this.stopSaveInterval();
    if (this.settings.isEnabled) {
      this.updateStatusBar("idle");
      this.saveInterval = setInterval(async () => {
        await this.saveCurrentWorkspace();
      }, this.settings.intervalSeconds * 1000);
    } else {
      this.updateStatusBar("disabled");
    }
  }
  stopSaveInterval() {
    clearInterval(this.saveInterval);
  }
  async saveCurrentWorkspace(manual = false) {
    const workspacesPlugin = this.getWorkspacesPlugin();
    if (!(workspacesPlugin == null ? void 0 : workspacesPlugin.enabled) || !workspacesPlugin.instance) {
      this.updateStatusBar("error");
      console.log("工作区插件未启用");
      if (manual && this.settings.showNotice) {
        new import_obsidian.Notice("工作区插件未启用", 2000);
      }
      return;
    }
    try {
      this.updateStatusBar("saving");

      await this.app.commands.executeCommandById("workspaces:save");

      console.log(`工作区已保存`);
      this.updateStatusBar("saved");
      if (this.settings.showNotice) {
        new import_obsidian.Notice("工作区已保存", 2000);
      }
      setTimeout(() => {
        if (this.settings.isEnabled) {
          this.updateStatusBar("idle");
        } else {
          this.updateStatusBar("disabled");
        }
      }, 2000);
    } catch (error) {
      this.updateStatusBar("error");
      console.error("保存工作区失败:", error);
      if (this.settings.showNotice) {
        new import_obsidian.Notice("保存工作区失败", 3000);
      }
    }
  }
  getWorkspacesPlugin() {
    return this.app.internalPlugins.plugins.workspaces;
  }
};
var IntervalWorkspaceSaverSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  addColorSetting(containerEl, key, name, desc) {
    const setting = new import_obsidian.Setting(containerEl).setName(name).setDesc(desc);
    setting.addText((text) => {
      text.inputEl.type = "color";
      const current = this.plugin.settings.colors[key] || "";
      text.setValue(current && current.trim() ? current : "#000000");
      text.onChange(async (value) => {
        this.plugin.settings.colors[key] = value;
        await this.plugin.saveSettings();
        this.plugin.applyStatusBarColors();
      });
    });
    setting.addButton((button) => {
      button.setButtonText("重置");
      button.onClick(async () => {
        this.plugin.settings.colors[key] = DEFAULT_SETTINGS.colors[key];
        await this.plugin.saveSettings();
        this.plugin.applyStatusBarColors();
        this.display();
      });
    });
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "间隔保存工作区设置" });
    new import_obsidian.Setting(containerEl).setName("启用插件").setDesc("启用或禁用间隔保存工作区功能").addToggle((toggle) => toggle.setValue(this.plugin.settings.isEnabled).onChange(async (value) => {
      this.plugin.settings.isEnabled = value;
      await this.plugin.saveSettings();
      this.plugin.startSaveInterval();
    }));
    new import_obsidian.Setting(containerEl).setName("保存间隔（秒）").setDesc("设置自动保存工作区的时间间隔（秒）").addText((text) => text.setPlaceholder("30").setValue(this.plugin.settings.intervalSeconds.toString()).onChange(async (value) => {
      const seconds = parseInt(value);
      if (!isNaN(seconds) && seconds > 0) {
        this.plugin.settings.intervalSeconds = seconds;
        await this.plugin.saveSettings();
        this.plugin.startSaveInterval();
      } else {
        new import_obsidian.Notice("请输入有效的秒数");
      }
    }));
    new import_obsidian.Setting(containerEl).setName("显示消息提醒").setDesc("保存工作区时是否显示消息提醒通知").addToggle((toggle) => toggle.setValue(this.plugin.settings.showNotice).onChange(async (value) => {
      this.plugin.settings.showNotice = value;
      await this.plugin.saveSettings();
    }));

    containerEl.createEl("h3", { text: "状态栏背景色（可选）" });
    containerEl.createEl("p", { text: "不选或重置=跟随主题默认配色；选择后仅修改背景色，不修改字体颜色。" });
    this.addColorSetting(containerEl, "idle", "待保存", "🔄️ 待保存 的背景色");
    this.addColorSetting(containerEl, "saving", "保存中", "💾 保存中 的背景色");
    this.addColorSetting(containerEl, "saved", "已保存", "✅ 已保存 的背景色");
    this.addColorSetting(containerEl, "error", "保存失败", "⚠️ 保存失败 的背景色");
    this.addColorSetting(containerEl, "disabled", "已禁用", "🔴 已禁用 的背景色");
    this.addColorSetting(containerEl, "notfound", "未找到工作区", "❌ 未找到工作区 的背景色");
  }
};
